# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"B\n\x13ValidateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1a\n\x12requesting_service\x18\x02 \x01(\t\"_\n\x14ValidateUserResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12!\n\tuser_info\x18\x02 \x01(\x0b\x32\x0e.user.UserInfo\x12\x15\n\rerror_message\x18\x03 \x01(\t\"J\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x11\n\tis_active\x18\x04 \x01(\x08\x32T\n\x0bUserService\x12\x45\n\x0cValidateUser\x12\x19.user.ValidateUserRequest\x1a\x1a.user.ValidateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VALIDATEUSERREQUEST']._serialized_start=20
  _globals['_VALIDATEUSERREQUEST']._serialized_end=86
  _globals['_VALIDATEUSERRESPONSE']._serialized_start=88
  _globals['_VALIDATEUSERRESPONSE']._serialized_end=183
  _globals['_USERINFO']._serialized_start=185
  _globals['_USERINFO']._serialized_end=259
  _globals['_USERSERVICE']._serialized_start=261
  _globals['_USERSERVICE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
