# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_pb2 as user__pb2


class UserServiceStub(object):
    """UserService provides user validation for other services
    Educational Note: This is used by OrderService to verify users exist
    before creating orders, without direct database access
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateUser = channel.unary_unary(
                '/user.UserService/ValidateUser',
                request_serializer=user__pb2.ValidateUserRequest.SerializeToString,
                response_deserializer=user__pb2.ValidateUserResponse.FromString,
                )


class UserServiceServicer(object):
    """UserService provides user validation for other services
    Educational Note: This is used by OrderService to verify users exist
    before creating orders, without direct database access
    """

    def ValidateUser(self, request, context):
        """Validate if a user exists and return basic info
        Educational Note: This is called via gRPC (not REST) because:
        1. Faster (binary protocol vs JSON)
        2. Type-safe (compile-time checking)
        3. Better for internal service-to-service calls
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateUser,
                    request_deserializer=user__pb2.ValidateUserRequest.FromString,
                    response_serializer=user__pb2.ValidateUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """UserService provides user validation for other services
    Educational Note: This is used by OrderService to verify users exist
    before creating orders, without direct database access
    """

    @staticmethod
    def ValidateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.UserService/ValidateUser',
            user__pb2.ValidateUserRequest.SerializeToString,
            user__pb2.ValidateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
