# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"D\n\x12ProductInfoRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x1a\n\x12requesting_service\x18\x02 \x01(\t\"h\n\x13ProductInfoResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12*\n\x0cproduct_info\x18\x02 \x01(\x0b\x32\x14.product.ProductInfo\x12\x15\n\rerror_message\x18\x03 \x01(\t\"z\n\x0bProductInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\t\x12\x17\n\x0finventory_count\x18\x05 \x01(\x05\x12\x14\n\x0cis_available\x18\x06 \x01(\x08\"W\n\x13\x41vailabilityRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x1a\n\x12requesting_service\x18\x03 \x01(\t\"\\\n\x14\x41vailabilityResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x1a\n\x12\x61vailable_quantity\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xaf\x01\n\x0eProductService\x12K\n\x0eGetProductInfo\x12\x1b.product.ProductInfoRequest\x1a\x1c.product.ProductInfoResponse\x12P\n\x11\x43heckAvailability\x12\x1c.product.AvailabilityRequest\x1a\x1d.product.AvailabilityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCTINFOREQUEST']._serialized_start=26
  _globals['_PRODUCTINFOREQUEST']._serialized_end=94
  _globals['_PRODUCTINFORESPONSE']._serialized_start=96
  _globals['_PRODUCTINFORESPONSE']._serialized_end=200
  _globals['_PRODUCTINFO']._serialized_start=202
  _globals['_PRODUCTINFO']._serialized_end=324
  _globals['_AVAILABILITYREQUEST']._serialized_start=326
  _globals['_AVAILABILITYREQUEST']._serialized_end=413
  _globals['_AVAILABILITYRESPONSE']._serialized_start=415
  _globals['_AVAILABILITYRESPONSE']._serialized_end=507
  _globals['_PRODUCTSERVICE']._serialized_start=510
  _globals['_PRODUCTSERVICE']._serialized_end=685
# @@protoc_insertion_point(module_scope)
