# Generated by Django 4.2.7 on 2026-01-01 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='Hashed backup token (PBKDF2-SHA256)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token was generated')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this token was used (null = unused)', null=True)),
                ('expires_at', models.DateTimeField(help_text='When this token expires (90 days from creation)')),
                ('user', models.ForeignKey(help_text='User who owns this backup token', on_delete=django.db.models.deletion.CASCADE, related_name='backup_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'used_at'], name='backup_toke_user_id_80702e_idx')],
            },
        ),
    ]
